### ISSUE TITLE
Create a draft "Search Result" page

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/oxo2#2]
This should be modelled after OLS 4: https://www.ebi.ac.uk/ols4/search/diabetes

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/7070631/218336322-bcccffac-77e2-4f1f-b9ac-ee838ac04f1b.png">

Only difference is, we should be able to search for more than one thing, i.e. https://www.ebi.ac.uk/spot/oxo?search=EFO:0000400,HP:0000819 or https://www.ebi.ac.uk/spot/oxo/terms/EFO:0000400,HP:0000819

**Comment by matentzn** [comment]
I would also like this to be possible:

https://www.ebi.ac.uk/spot/oxo/terms/EFO:0000400 (showing all mappings from or to EFO:0000400) 
https://www.ebi.ac.uk/spot/oxo/terms/EFO:0000400/skos:exactMatch (showing all _exact_ mappings from or to EFO:0000400) 
https://www.ebi.ac.uk/spot/oxo/terms/EFO:0000400/skos:exactMatch/MONDO:0005015 (showing any information we have on the `EFO:0000400--[skos:exactMatch]-->MONDO:0005015`, i.e. the same as this page: https://www.ebi.ac.uk/spot/oxo/mappings/2850743 in the Old OxO)

**Comment by matentzn** [comment]
I will start making suggestions once the API is integrated. This looks very cool!

**Comment by serjoshua** [comment]
I will be closing this ticket to properly monitor integration of backend (API) to the frontend changes. I recommend creating separate issues/requests for API integration.
