### ISSUE TITLE
All UI elements should render CURIEs, not URIs

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/oxo2#28]
ask @anitacaron if you need help with this

**Comment by matentzn** [comment]
Don't use uri hacking for this, always use curie maps!

**Comment by serjoshua** [comment]
Apologies. I'll talk to Anita about this then. She might have to add it in response. Thanks.

**Comment by anitacaron** [comment]
I wonder why this is part of the UI. I was planning to use the curies lib for this.

**Comment by anitacaron** [comment]
It's already on the [TODO list](https://github.com/anitacaron/sssom-api/issues/36). We can close this issue as not planned.

**Comment by matentzn** [comment]
Predicate id is important!

**Comment by anitacaron** [comment]
We know, but it's not part of the curie lib.

**Comment by matentzn** [comment]
You know best - as for the curies lib we should in any case use our own context, not the default one
