### ISSUE TITLE
Create mapping info page placeholder

### ISSUE THREAD

**Issue by serjoshua** [EBISPOT/oxo2#8]

**Comment by serjoshua** [comment]
<img width="927" alt="Screen Shot 2023-02-28 at 11 02 25 AM" src="https://user-images.githubusercontent.com/25520595/221835467-f8b48eb1-2ddf-41b1-9874-dea87e4f9190.png">

**Comment by matentzn** [comment]
One thing that is critical is that every single page is identifiable by a URL.
